FROM packt-beam-base:latest

ADD chapter*/target/*.jar /usr/local/lib/
ADD */target/*.jar /usr/local/lib/
ADD chapter*/src/main/python/* /usr/local/bin/
ADD chapter6/src/main/python/dist/*.tar.gz /usr/local/bin/
ADD chapter1/src/main/resources/lorem.txt /usr/share/

